# These are supported funding model platforms

github: [CreatorOss]
custom: ["https://paypal.me/Sendec?country.x=ID&locale.x=id_ID", "https://buymeacoffee.com/creatoross", "mailto:enterprise@certifycli.com"]